/** @type {import('next').NextConfig} */
const nextConfig = {
  serverExternalPackages: ["@react-pdf/renderer"],

  // Inclui o worker e TODAS as dependências transitivas no bundle serverless (Vercel)
  outputFileTracingIncludes: {
    "/api/curriculo": [
      "./scripts/**/*",
      "./node_modules/@react-pdf/**/*",
      "./node_modules/@babel/runtime/**/*",
      "./node_modules/@noble/**/*",
      "./node_modules/@swc/helpers/**/*",
      "./node_modules/abs-svg-path/**/*",
      "./node_modules/base64-js/**/*",
      "./node_modules/bidi-js/**/*",
      "./node_modules/brotli/**/*",
      "./node_modules/browserify-zlib/**/*",
      "./node_modules/clone/**/*",
      "./node_modules/color-name/**/*",
      "./node_modules/color-string/**/*",
      "./node_modules/dfa/**/*",
      "./node_modules/emoji-regex-xs/**/*",
      "./node_modules/events/**/*",
      "./node_modules/fast-deep-equal/**/*",
      "./node_modules/fflate/**/*",
      "./node_modules/fontkit/**/*",
      "./node_modules/hsl-to-hex/**/*",
      "./node_modules/hsl-to-rgb-for-reals/**/*",
      "./node_modules/hyphen/**/*",
      "./node_modules/inherits/**/*",
      "./node_modules/is-url/**/*",
      "./node_modules/jay-peg/**/*",
      "./node_modules/js-md5/**/*",
      "./node_modules/js-tokens/**/*",
      "./node_modules/linebreak/**/*",
      "./node_modules/loose-envify/**/*",
      "./node_modules/media-engine/**/*",
      "./node_modules/normalize-svg-path/**/*",
      "./node_modules/object-assign/**/*",
      "./node_modules/pako/**/*",
      "./node_modules/parse-svg-path/**/*",
      "./node_modules/png-js/**/*",
      "./node_modules/postcss-value-parser/**/*",
      "./node_modules/prop-types/**/*",
      "./node_modules/queue/**/*",
      "./node_modules/react/**/*",
      "./node_modules/react-is/**/*",
      "./node_modules/require-from-string/**/*",
      "./node_modules/restructure/**/*",
      "./node_modules/safe-buffer/**/*",
      "./node_modules/scheduler/**/*",
      "./node_modules/string_decoder/**/*",
      "./node_modules/svg-arc-to-cubic-bezier/**/*",
      "./node_modules/tiny-inflate/**/*",
      "./node_modules/tslib/**/*",
      "./node_modules/unicode-properties/**/*",
      "./node_modules/unicode-trie/**/*",
      "./node_modules/util-deprecate/**/*",
      "./node_modules/vite-compatible-readable-stream/**/*",
      "./node_modules/yoga-layout/**/*",
    ],
  },
};

module.exports = nextConfig
